apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-depl
  #spicification for deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        #spicification for pod
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
